version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: taskmanager-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: taskmanager
    volumes:
      - mongodb_data:/data/db
    networks:
      - taskmanager-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: taskmanager-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/taskmanager
      JWT_SECRET: your-super-secret-jwt-key-here
      JWT_EXPIRES_IN: 7d
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - taskmanager-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: taskmanager-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5000/api
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - taskmanager-network

volumes:
  mongodb_data:

networks:
  taskmanager-network:
    driver: bridge
